// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/policymanager.proto

package policy_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PolicyManagerClient is the client API for PolicyManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyManagerClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
}

type policyManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyManagerClient(cc grpc.ClientConnInterface) PolicyManagerClient {
	return &policyManagerClient{cc}
}

func (c *policyManagerClient) GetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, "/policymanager.PolicyManager/GetPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyManagerServer is the server API for PolicyManager service.
// All implementations must embed UnimplementedPolicyManagerServer
// for forward compatibility
type PolicyManagerServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error)
	mustEmbedUnimplementedPolicyManagerServer()
}

// UnimplementedPolicyManagerServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyManagerServer struct {
}

func (UnimplementedPolicyManagerServer) GetPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedPolicyManagerServer) mustEmbedUnimplementedPolicyManagerServer() {}

// UnsafePolicyManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyManagerServer will
// result in compilation errors.
type UnsafePolicyManagerServer interface {
	mustEmbedUnimplementedPolicyManagerServer()
}

func RegisterPolicyManagerServer(s grpc.ServiceRegistrar, srv PolicyManagerServer) {
	s.RegisterService(&PolicyManager_ServiceDesc, srv)
}

func _PolicyManager_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyManagerServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policymanager.PolicyManager/GetPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyManagerServer).GetPolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyManager_ServiceDesc is the grpc.ServiceDesc for PolicyManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policymanager.PolicyManager",
	HandlerType: (*PolicyManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicy",
			Handler:    _PolicyManager_GetPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/policymanager.proto",
}
